#! /bin/sh

bspc monitor -d I II III IV V VI

feh --bg-fill $HOME/.background/cafe.jpg
$HOME/.config/polybar/launch.sh

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
#bspc config border_radius 		 6

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a discord desktop='^4'
#bspc rule -a TelegramDesktop desktop='^4'

xsetroot -cursor_name left_ptr &
xautolock -detectsleep -time 10 -locker "/home/zuper/.config/polybar/scripts/lock.sh" -notify 30 -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" &
picom &
flameshot &
dunst &
